"""
Automatic audit report for ZH/Dialog/ep1-6 (240 sentences).

Checks:
  1. 209 한자 초과 — 본문에서 209 set 외 한자 추출 (인명·지명 분리)
  2. 어기조사·부르기 13종 실제 카운트 (ep별 + 통합)
  3. 중국어 문장부호 통일 (, ? ! → ，？！)
  4. 한국어 직역투 검출 (휴리스틱)
  5. 문장 길이 분포 (너무 길거나 짧은 비율)
  6. 캐릭터 호칭 일관성 (Lily vs 小丽)
  7. 본문/통계 불일치 식별

Output: ZH/Dialog/_audit_report.md
"""
import re, json, os
from collections import Counter, defaultdict

ZH_DIR = r"D:/OneDrive/PROJECT/talkverse-learning/ZH"
HANZI_JSON = f"{ZH_DIR}/Word/core_hanzi_209.json"
DIALOG_DIR = f"{ZH_DIR}/Dialog"
OUT = f"{DIALOG_DIR}/_audit_report.md"

# 1) Load 209 set
with open(HANZI_JSON, encoding="utf-8") as f:
    data = json.load(f)
set209 = set(c["char"] for c in data["characters"])

# 2) Particle/greeting 13 set
PARTICLES = list("吗吧啊呀呢啦嗯嘛哦哪")
GREETINGS = list("喂嘿嗨")
ALL_PG = PARTICLES + GREETINGS

# 3) Parse each ep markdown — extract dialogue rows
EPS = ["ep1_matching", "ep2_meal", "ep3_family", "ep4_conflict", "ep5_future", "ep6_routine"]
# table row pattern: "| 1 | 你好啊! | Nǐ hǎo a! | 안녕하세요! | ..."
ROW_RE = re.compile(r"^\|\s*(\d+)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|", re.MULTILINE)

CJK = re.compile(r"[一-鿿]")

ep_rows = {}     # ep -> list of (num, zh, py, ko)
all_zh_chars = []
ep_chars = defaultdict(list)

for ep in EPS:
    path = f"{DIALOG_DIR}/{ep}.md"
    with open(path, encoding="utf-8") as f:
        text = f.read()
    rows = []
    for m in ROW_RE.finditer(text):
        num, zh, py, ko = m.group(1), m.group(2), m.group(3), m.group(4)
        # strip markdown bold
        zh_clean = re.sub(r"\*+", "", zh).strip()
        rows.append((int(num), zh_clean, py.strip(), ko.strip()))
        chars = [c for c in zh_clean if CJK.match(c)]
        all_zh_chars.extend(chars)
        ep_chars[ep].extend(chars)
    ep_rows[ep] = rows

# === Check 1: 한자 초과 ===
all_chars_used = Counter(all_zh_chars)
over_209 = {c: n for c, n in all_chars_used.items() if c not in set209}
in_209 = {c: n for c, n in all_chars_used.items() if c in set209}
total_char_tokens = sum(all_chars_used.values())
over_tokens = sum(over_209.values())

# 209 외 자연 노출 허용 화이트리스트 (인명·지명·문화·가족 호칭 등)
NATURAL_EXPOSURE = set(
    "丽红海韩国"        # 인명·지명: 小丽·小红·上海·韩国
    "咖啡饺"           # 음식: 咖啡·饺子
    "您叔阿姨奶爷妹哥"   # 가족 호칭 단자
    "设计师文学识"      # 직업·학습: 设计师·文化·学·认识
    "周末月日六"        # 시간: 周末·月底·周六
    "约会结婚"          # 핵심 사건: 约会·结婚·约定
    "麻哈哎哦"          # 감탄·hook: 哈哈·哎呀
    "嗨喂"              # 부르기 (어기조사 표 참조)
    "忘"                # 忘 — 자주 등장
    "近店附"            # 장소: 附近·咖啡店
    "客气坐喝试慢"      # 식사 예절
    "孤独忙紧张"        # 감정 동사
    "笑早午"            # 기타 자주
    "几"                # 수사 보조
    # ep6 일상·HSKK 보강 자연 노출
    "雨雪伞班车站路"     # 날씨·교통: 下雨·下雪·伞·上班·上车·车站·路上
    "馆面辣饭"          # 음식·식당: 面馆·辣·饭
    "王老板努力公"      # 직장: 王哥·老板·努力·公司
    "迟手机楼喽睡七半"  # 일상: 迟到·手机·楼下·上车喽·睡·7点·一半
    "般"                # 一般
)
allowed = {c: n for c, n in over_209.items() if c in NATURAL_EXPOSURE}
unreviewed = {c: n for c, n in over_209.items() if c not in NATURAL_EXPOSURE}

# === Check 2: Particle/greeting count ===
particle_counts_global = Counter()
particle_counts_per_ep = defaultdict(Counter)
for ep in EPS:
    text = " ".join(r[1] for r in ep_rows[ep])
    for p in ALL_PG:
        n = text.count(p)
        particle_counts_global[p] += n
        particle_counts_per_ep[ep][p] = n

# === Check 3: Punctuation 통일 ===
PUNCT_BAD = ['?', '!', "'", '"']  # ASCII 기호 (중국어 본문엔 ，？！""권장)
ASCII_PUNCT_PER_EP = defaultdict(int)
for ep in EPS:
    for r in ep_rows[ep]:
        zh = r[1]
        for p in PUNCT_BAD:
            ASCII_PUNCT_PER_EP[ep] += zh.count(p)

# === Check 4: Sentence length distribution ===
lengths = []
for ep in EPS:
    for r in ep_rows[ep]:
        zh_only = "".join(c for c in r[1] if CJK.match(c))
        lengths.append(len(zh_only))
import statistics
len_stats = {
    "min": min(lengths),
    "max": max(lengths),
    "mean": statistics.mean(lengths),
    "median": statistics.median(lengths),
    "≤2자": sum(1 for L in lengths if L <= 2),
    "3-5자": sum(1 for L in lengths if 3 <= L <= 5),
    "6-10자": sum(1 for L in lengths if 6 <= L <= 10),
    "11+자": sum(1 for L in lengths if L >= 11),
}

# === Check 5: 호칭 일관성 (Lily vs 小丽) ===
naming = {"Lily_appearance": 0, "小丽_appearance": 0}
for ep in EPS:
    for r in ep_rows[ep]:
        if "Lily" in r[1]: naming["Lily_appearance"] += 1
        if "小丽" in r[1]: naming["小丽_appearance"] += 1

# === Build markdown report ===
out = []
out.append("# ZH Dialog 자동 검증 리포트 (240문장 ep1-6)\n")
out.append(f"> Generated by `scripts/22_dialog_audit.py` (자동)\n")
out.append("")

# 1. 한자 초과
out.append("## 1. 209 한자 초과 사용 한자 (본문 기준)\n")
out.append(f"- 총 한자 토큰: {total_char_tokens}")
out.append(f"- 209 안 한자 종류: {len(in_209)}/209")
out.append(f"- **209 외 한자 종류: {len(over_209)}**")
out.append(f"- 209 외 토큰 비율: {over_tokens}/{total_char_tokens} = {over_tokens/total_char_tokens*100:.1f}%\n")
out.append(f"  - 자연 노출 허용: {sum(allowed.values())} 토큰 ({len(allowed)} 종)")
out.append(f"  - **재검토 필요: {sum(unreviewed.values())} 토큰 ({len(unreviewed)} 종)**\n")
out.append("### 209 외 한자 — 자연 노출 허용 (인명·지명·문화·가족 등)\n")
out.append("| 한자 | 횟수 | 분류 |")
out.append("|---|---:|---|")
for c, n in sorted(allowed.items(), key=lambda x: -x[1])[:30]:
    out.append(f"| {c} | {n} | 자연노출 |")
out.append("\n### 209 외 한자 — 재검토 필요\n")
if unreviewed:
    out.append("| 한자 | 횟수 |")
    out.append("|---|---:|")
    for c, n in sorted(unreviewed.items(), key=lambda x: -x[1])[:30]:
        out.append(f"| {c} | {n} |")
else:
    out.append("(없음 — 모두 자연 노출 허용 목록에 포함)")
out.append("")

# 2. 어기조사·부르기 카운트
out.append("\n## 2. 어기조사·부르기 13종 카운트 (실제 본문)\n")
out.append("| 글자 | 종류 | ep1 | ep2 | ep3 | ep4 | ep5 | ep6 | 합계 |")
out.append("|---|---|---:|---:|---:|---:|---:|---:|---:|")
for p in PARTICLES:
    row = [p, "어기"]
    for ep in EPS:
        row.append(str(particle_counts_per_ep[ep][p]))
    row.append(f"**{particle_counts_global[p]}**")
    out.append("| " + " | ".join(row) + " |")
for p in GREETINGS:
    row = [p, "부르기"]
    for ep in EPS:
        row.append(str(particle_counts_per_ep[ep][p]))
    row.append(f"**{particle_counts_global[p]}**")
    out.append("| " + " | ".join(row) + " |")
out.append("")

# 3. 문장부호
out.append("\n## 3. 문장부호 ASCII 사용 (중국어 본문 → ，？！“”로 통일 권장)\n")
out.append("| ep | ASCII 기호 (`,?!'\"`) 개수 |")
out.append("|---|---:|")
for ep in EPS:
    out.append(f"| {ep} | {ASCII_PUNCT_PER_EP[ep]} |")
out.append("")

# 4. 문장 길이
out.append("\n## 4. 문장 길이 분포 (한자 기준)\n")
out.append(f"- 최소: {len_stats['min']}자")
out.append(f"- 최대: {len_stats['max']}자")
out.append(f"- 평균: {len_stats['mean']:.1f}자")
out.append(f"- 중앙: {len_stats['median']:.1f}자")
out.append("")
out.append("| 구간 | 개수 | 비율 |")
out.append("|---|---:|---:|")
for k in ["≤2자", "3-5자", "6-10자", "11+자"]:
    out.append(f"| {k} | {len_stats[k]} | {len_stats[k]/240*100:.1f}% |")
out.append("")

# 5. 호칭 일관성
out.append("\n## 5. 호칭 일관성 (Lily vs 小丽)\n")
out.append(f"- Lily 등장: {naming['Lily_appearance']}회")
out.append(f"- 小丽 등장: {naming['小丽_appearance']}회")
out.append("- ⚠️ ep1 #35-37에서 Lily 실수 hook 후 ep5 #181에 다시 Lily 등장 — 일관성 검토")
out.append("")

# 6. 본문/통계 불일치 (수동 검증 필요 — 자동은 어려움)
out.append("\n## 6. 알려진 본문/통계 불일치 (수동 확인 필요)\n")
out.append("- ep1 통계: 才·已·又·只 (본문 미등장)")
out.append("- ep2 hook 위치: #15 (실제 #66-67)")
out.append("- ep4 어기조사: 13종 모두 등장 → 실제 8종만 (吧·吗·呢·啦·嗯·呀·喂·啊)")
out.append("- ep5 통계: 嫁给我吧, 真的吗啊 (본문 미등장)")
out.append("")

# 7. 권장 조치
out.append("\n## 7. 권장 조치 (우선순위)\n")
out.append("1. **209 외 한자 빈도 ≥10인 것 → 학습 한자 풀에 추가 검토** (예: 中·国·大·家·小·点·明·边·下·去 등 자주 쓰이지만 209 밖일 가능성)")
out.append("2. **어기조사 실제 카운트 = 본문 통계 일치하도록 ep1-5 상단/하단 통계 자동 재생성**")
out.append("3. **ASCII 문장부호 → 중국어 표준 ，。？！“”로 일괄 변환** (sed)")
out.append("4. **Lily vs 小丽 일관성 재검토** (ep1 hook + ep5 #181)")
out.append("5. **이 리포트를 정기 실행** (다이얼로그 수정 시마다)")

# Save
with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(out))
print(f"[done] saved -> {OUT} ({os.path.getsize(OUT):,} bytes)")
print()
print(f"=== 핵심 통계 ===")
print(f"총 한자 토큰: {total_char_tokens}")
print(f"209 외 한자 종류: {len(over_209)}")
print(f"209 외 토큰 비율: {over_tokens/total_char_tokens*100:.1f}%")
print(f"평균 문장 길이: {len_stats['mean']:.1f}자")
print()
print(f"=== 209 외 빈도 상위 20 ===")
for c, n in sorted(over_209.items(), key=lambda x: -x[1])[:20]:
    print(f"  {c}: {n}회")
print()
print(f"=== 어기조사·부르기 합계 ===")
for p in ALL_PG:
    print(f"  {p}: {particle_counts_global[p]}회")
